spring.application.name=goldsmith-backend
server.port=${PORT:8080}

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=goldsmithDB

logging.level.org.springframework.data.mongodb=INFO